version: '3'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - '5672:5672'
    environment:
      - 'RABBITMQ_PASSWORD:secret'
      - 'RABBITMQ_USERNAME:admin'
    volumes:
      - 'rabbitmq_data:/bitnami'
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
      - ./init/cassandra:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_CLUSTER_NAME=notificationCluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
volumes:
  rabbitmq_data:
    driver: local
  cassandra_data:
    driver: local
