version: '3'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - '5672:5672'
    environment:
      - 'RABBITMQ_PASSWORD:secret'
      - 'RABBITMQ_USERNAME:admin'
    volumes:
      - 'rabbitmq_data:/bitnami'
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
      - ./init/cassandra:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - CASSANDRA_DATACENTER=${CASSANDRA_DATACENTER}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
volumes:
  rabbitmq_data:
    driver: local
  cassandra_data:
    driver: local
